# Generated by Django 3.1.5 on 2021-03-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_register_courses',
            name='order_id',
            field=models.TextField(null=True),
        ),
    ]
